### ISSUE TITLE
Input style: Number and 24h mode is  

### ISSUE THREAD

**Issue by marcospoel** [kareesnc/SimpleTimeWidget#1]
![error-1](https://user-images.githubusercontent.com/21373624/156925883-be4a483b-7746-4ff1-a556-129edd8b6d3a.png)
![error-2](https://user-images.githubusercontent.com/21373624/156925893-bae19c92-ad22-43e9-ac42-4f156a9fefa9.png)

**Comment by kareesnc** [comment]
Fixed in release 1.1.1
